"""storyline_overlay.v1 — interpretive overlay records for storylines.

A storyline = a worldline backbone (grounded, derived, evidence-backed) plus
interpretive overlays generated by the dreamer and accepted through the
explicit decide flow. Overlays are the "what does it mean" layer; the
backbone is the "what happened" layer.

Epistemic rules encoded here:
- **Traceability is mandatory.** An overlay with no supporting worldlines or
  beads is invalid at this gate — interpretation must point at the history it
  interprets.
- **Overlays are never grounded objects.** They are not beads, claims, or
  associations, and they must never be inputs to backbone derivation (the
  one-way rule; enforced by storage layout and tests, stated here for
  readers). Naming note: these are deliberately NOT called "observations" —
  the grounded `structured-observation` ingest type is a different, factual
  thing.
- **Revisable, not mutable.** Overlays are append-only; a revision is a new
  record carrying ``supersedes_overlay_id``. History is retained — the
  sequence of interpretations is itself a worldline.
- **Falsifiable.** ``expected_revision_triggers`` states what would change
  this interpretation.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

STORYLINE_OVERLAY_SCHEMA = "storyline_overlay.v1"

OVERLAY_KINDS = {"narrative", "value", "attractor", "tension_note"}

ERROR_OVERLAY_UNTRACEABLE = "storyline_overlay_untraceable"
ERROR_OVERLAY_INVALID = "storyline_overlay_invalid"

MAX_OVERLAY_TITLE_CHARS = 160


def validate_storyline_overlay(record: dict[str, Any]) -> tuple[bool, str, dict[str, Any]]:
    """Validate an overlay record. Returns (ok, error_code, details)."""
    if not isinstance(record, dict):
        return False, ERROR_OVERLAY_INVALID, {"reason": "not_a_dict"}
    if str(record.get("schema") or "") != STORYLINE_OVERLAY_SCHEMA:
        return False, ERROR_OVERLAY_INVALID, {"reason": "bad_schema", "schema": record.get("schema")}
    kind = str(record.get("kind") or "").strip().lower()
    if kind not in OVERLAY_KINDS:
        return False, ERROR_OVERLAY_INVALID, {"reason": "bad_kind", "kind": kind}
    statement = str(record.get("statement") or "").strip()
    if not statement:
        return False, ERROR_OVERLAY_INVALID, {"reason": "empty_statement"}
    title = record.get("title")
    if title is not None and (not isinstance(title, str) or len(title) > MAX_OVERLAY_TITLE_CHARS):
        return False, ERROR_OVERLAY_INVALID, {"reason": "bad_title"}
    worldlines = [str(x) for x in (record.get("supporting_worldline_ids") or []) if str(x).strip()]
    beads = [str(x) for x in (record.get("supporting_bead_ids") or []) if str(x).strip()]
    if not worldlines or not beads:
        # The hard gate: interpretation without history is not admissible.
        return False, ERROR_OVERLAY_UNTRACEABLE, {
            "reason": "missing_support",
            "worldlines": len(worldlines),
            "beads": len(beads),
        }
    try:
        confidence = float(record.get("confidence"))
    except (TypeError, ValueError):
        return False, ERROR_OVERLAY_INVALID, {"reason": "bad_confidence"}
    if not (0.0 <= confidence <= 1.0):
        return False, ERROR_OVERLAY_INVALID, {"reason": "confidence_out_of_range", "confidence": confidence}
    return True, "", {}


def build_storyline_overlay(
    *,
    kind: str,
    statement: str,
    supporting_worldline_ids: list[str],
    supporting_bead_ids: list[str],
    confidence: float,
    title: str = "",
    convergence_key: str = "",
    expected_revision_triggers: list[str] | None = None,
    supersedes_overlay_id: str | None = None,
    run_metadata: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Construct a well-formed overlay record (caller still validates)."""
    return {
        "schema": STORYLINE_OVERLAY_SCHEMA,
        "id": f"ovl-{uuid.uuid4().hex[:12]}",
        "kind": str(kind).strip().lower(),
        "title": str(title or "").strip()[:MAX_OVERLAY_TITLE_CHARS] or None,
        "statement": str(statement).strip(),
        "supporting_worldline_ids": [str(x) for x in supporting_worldline_ids if str(x).strip()],
        "supporting_bead_ids": [str(x) for x in supporting_bead_ids if str(x).strip()],
        "confidence": float(confidence),
        "convergence_key": str(convergence_key or ""),
        "expected_revision_triggers": [str(t).strip() for t in (expected_revision_triggers or []) if str(t).strip()],
        "supersedes_overlay_id": str(supersedes_overlay_id or "") or None,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "run_metadata": dict(run_metadata or {}),
    }
